events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream home_app {
        server home-app:3000;
    }

    upstream worker_8081 {
        server game-worker-1:8081;
    }

    upstream worker_8082 {
        server game-worker-2:8082;
    }

    upstream worker_8083 {
        server game-worker-3:8083;
    }

    upstream worker_8084 {
        server game-worker-4:8084;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://home_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ~ ^/ws-connect/8081(.*) {
            proxy_pass http://worker_8081$1;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location ~ ^/ws-connect/8082(.*) {
            proxy_pass http://worker_8082$1;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location ~ ^/ws-connect/8083(.*) {
            proxy_pass http://worker_8083$1;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location ~ ^/ws-connect/8084(.*) {
            proxy_pass http://worker_8084$1;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
